[package]
name = "legion"
version = "0.1.1"
description = "High performance entity component system (ECS) library"
authors = ["Thomas Gillen <thomas.gillen@googlemail.com>"]
repository = "https://github.com/TomGillen/legion"
keywords = ["ecs", "game"]
categories = ["game-engines", "data-structures"]
readme = "readme.md"
license = "MIT"
edition = "2018"

[lib]
crate_type = ["cdylib", "lib"]

[badges]
travis-ci = { repository = "TomGillen/legion", branch = "master" }

[features]
default = ["par-iter", "c-api", "schedule", "blanket-impl-comp"]
par-iter = ["rayon"]
c-api = ["easy_ffi"]
schedule = ["petgraph", "hibitset"]
blanket-impl-comp = []

[dependencies]
slog = { version = "2.4", features = ["max_level_trace", "release_max_level_info", "nested-values"] }
slog-stdlog = "3"
parking_lot = "0.7"
downcast-rs = "1.0"
itertools = "0.8"
names = "0.11.0"
rayon = { version = "1.0", optional = true }
fnv = "1.0"
easy_ffi = { version = "0.1.0", optional = true }
petgraph = { version = "0.4", optional = true }
hibitset = { version = "0.6", optional = true }

[dev-dependencies]
env_logger = "0.6"
slog-term = "2"
slog-async = "2"
criterion = "0.2"
cgmath = "0.17"

[[bench]]
name = "benchmarks"
harness = false

[[bench]]
name = "parallel_query"
harness = false

[[bench]]
name = "transform"
harness = false
